#!/usr/bin/env bash
. ./lib.sh

cat > providing <<EOF
col1	col2
1	4
2	5
3	6
EOF

start_nodes providing

(
	client_gen_network
	client survey new test-run-survey |
		client survey set-sources col2 |
		client survey set-operation sum
) | client survey run |
	xargs -t test $(((4+5+6) * (node_count-1))) -eq
