#!/usr/bin/env bash
. ./lib.sh

cat > providing <<EOF
col1	col2	col3
1	4	-2
2	5	-4
3	6	-6
EOF

start_nodes providing

(
	client_gen_network
	client survey new test-run-survey |
		client survey set-sources col{1,3} |
		client survey set-operation cosim
) | client survey run |
	xargs -t test -0.9999999999999999 =
