#!/usr/bin/env bash
. ./lib.sh

cat > providing <<EOF
name
1
2
3
EOF

start_nodes providing

(
	client_gen_network
	client survey new test |
		client survey set-sources unknown |
		client survey set-operation sum
) | client survey run |
	xargs test 0 -eq
