#!/usr/bin/env bash
. ./lib.sh

cat > providing <<EOF
1
2
3
EOF

start_nodes providing

(
	client_gen_network
	client survey new test-run-survey |
		client survey set-operation sum
) | client survey run |
	xargs test $(((1+2+3) * (node_count-1))) -eq
